# Generated by Django 5.2.7 on 2025-11-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyapp', '0006_notification_is_read_profile_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideresponse',
            name='response',
            field=models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined')], max_length=20),
        ),
    ]
