# Generated by Django 5.2.7 on 2025-12-01 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyapp', '0008_riderequest_accepter_riderequest_accepter_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ride_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='buddyapp.riderequest'),
        ),
    ]
